spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proyectospring?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Secret_123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      
  profiles:    active:    - development